### ISSUE TITLE
Cannot run server on MacOS

### ISSUE THREAD

**Issue by cactuspoint** [iommu/CSCI334Project#22]
```
% cd CSCI334Project/server

% brew install poetry

% poetry install     
Creating virtualenv server-h2SrD1F4-py3.9 in /Users/paul/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file
Package operations: 33 installs, 0 updates, 0 removals
  • Installing six (1.16.0)
  • Installing promise (2.3)
  • Installing rx (1.6.1)
  • Installing graphql-core (2.3.2)
  • Installing markupsafe (2.0.0)
  • Installing aniso8601 (7.0.0)
  • Installing click (8.0.0)
  • Installing graphql-relay (2.0.1)
  • Installing greenlet (1.1.0)
  • Installing itsdangerous (2.0.0)
  • Installing jinja2 (3.0.0)
  • Installing pyparsing (2.4.7)
  • Installing werkzeug (2.0.1)
  • Installing attrs (21.2.0)
  • Installing certifi (2020.12.5)
  • Installing chardet (4.0.0)
  • Installing flask (2.0.0)
  • Installing graphene (2.1.8)
  • Installing graphql-server-core (1.2.0)
  • Installing idna (2.10)
  • Installing more-itertools (8.7.0)
  • Installing packaging (20.9)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing singledispatch (3.6.1)
  • Installing sqlalchemy (1.4.15)
  • Installing urllib3 (1.26.4)
  • Installing wcwidth (0.2.5)
  • Installing flask-graphql (2.0.1)
  • Installing graphene-sqlalchemy (2.3.0)
  • Installing pyjwt (2.1.0)
  • Installing pytest (5.4.3)
  • Installing requests (2.25.1)

% poetry run ./main.py         
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from gql_server.app import create_server
  File "/Users/paul/code/CSCI334Project/server/gql_server/app.py", line 3, in <module>
    from flask import Flask, request, safe_join, send_file
ModuleNotFoundError: No module named 'flask' 
```

**Comment by cactuspoint** [comment]
```
% python requirements.txt 
  File "/Users/paul/code/CSCI334Project/server/requirements.txt", line 1
    aniso8601==7.0.0 \
                  ^
SyntaxError: invalid syntax
```

**Comment by cactuspoint** [comment]
```
% python -V
Python 3.9.5

% pip install -r requirements.txt
Ignoring colorama: markers 'python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0"' don't match your environment
Collecting aniso8601==7.0.0
  Downloading aniso8601-7.0.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.7 MB/s 
Collecting certifi==2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 3.7 MB/s 
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 6.1 MB/s 
Collecting click==8.0.0
  Downloading click-8.0.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 5.4 MB/s 
Collecting flask-graphql==2.0.1
  Downloading Flask-GraphQL-2.0.1.tar.gz (6.1 kB)
Collecting flask==2.0.0
  Downloading Flask-2.0.0-py3-none-any.whl (93 kB)
     |████████████████████████████████| 93 kB 4.6 MB/s 
Collecting graphene-sqlalchemy==2.3.0
  Downloading graphene_sqlalchemy-2.3.0-py2.py3-none-any.whl (38 kB)
Collecting graphene==2.1.8
  Downloading graphene-2.1.8-py2.py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 5.9 MB/s 
Collecting graphql-core==2.3.2
  Downloading graphql_core-2.3.2-py2.py3-none-any.whl (252 kB)
     |████████████████████████████████| 252 kB 5.6 MB/s 
Collecting graphql-relay==2.0.1
  Downloading graphql_relay-2.0.1-py3-none-any.whl (20 kB)
Collecting graphql-server-core==1.2.0
  Downloading graphql-server-core-1.2.0.tar.gz (7.0 kB)
Collecting greenlet==1.1.0
  Downloading greenlet-1.1.0.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 3.4 MB/s 
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 4.0 MB/s 
Collecting itsdangerous==2.0.0
  Downloading itsdangerous-2.0.0-py3-none-any.whl (18 kB)
Collecting jinja2==3.0.0
  Downloading Jinja2-3.0.0-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 3.2 MB/s 
Collecting markupsafe==2.0.0
  Downloading MarkupSafe-2.0.0-cp39-cp39-macosx_10_9_universal2.whl (18 kB)
Collecting promise==2.3
  Downloading promise-2.3.tar.gz (19 kB)
Collecting pyjwt==2.1.0
  Downloading PyJWT-2.1.0-py3-none-any.whl (16 kB)
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 3.9 MB/s 
Collecting rx==1.6.1
  Downloading Rx-1.6.1-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 2.9 MB/s 
Collecting singledispatch==3.6.1
  Downloading singledispatch-3.6.1-py2.py3-none-any.whl (9.5 kB)
Requirement already satisfied: six==1.16.0 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 143)) (1.16.0)
Collecting sqlalchemy==1.4.15
  Downloading SQLAlchemy-1.4.15.tar.gz (7.6 MB)
     |████████████████████████████████| 7.6 MB 368 kB/s 
Collecting urllib3==1.26.4
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 8.4 MB/s 
Requirement already satisfied: werkzeug==2.0.1 in /opt/homebrew/lib/python3.9/site-packages (from -r requirements.txt (line 180)) (2.0.1)
Building wheels for collected packages: flask-graphql, graphql-server-core, greenlet, promise, sqlalchemy
  Building wheel for flask-graphql (setup.py) ... done
  Created wheel for flask-graphql: filename=Flask_GraphQL-2.0.1-py3-none-any.whl size=6367 sha256=3863beabceb4e56223862770215153c0594daeed10b9a21198f9e19306f3ffed
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/a1/19/f5/ee40fd8c5124431538b0634273ea14f2feaaca9280463c724b
  Building wheel for graphql-server-core (setup.py) ... done
  Created wheel for graphql-server-core: filename=graphql_server_core-1.2.0-py2.py3-none-any.whl size=7535 sha256=90d65033b08f754111fdccf6db48790a2d10ea1a4ba0ca3ddde6d74cb1fd1ef3
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/f4/22/c7/563db6b5c8164b4a2e711da765fb1d6d4e44f0ee6c0232ce91
  Building wheel for greenlet (setup.py) ... done
  Created wheel for greenlet: filename=greenlet-1.1.0-cp39-cp39-macosx_11_0_arm64.whl size=88832 sha256=28a6d308f39743f61d2975fa5489bae3cbc1483dea9a08655cd09bf1ad30bcea
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/79/88/67/99d62e1ad322548af24e31f462acc567159cf0f859e5b70f81
  Building wheel for promise (setup.py) ... done
  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=26d8664b9b4df50508b855e9b44c0800b1245c9dfb43c9f45d22b349cee255c9
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/e1/e8/83/ddea66100678d139b14bc87692ece57c6a2a937956d2532608
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.15-cp39-cp39-macosx_11_0_arm64.whl size=1476549 sha256=b2913d24cdecbe1f5875d522bc7bc8006739e45ff09f0d3f086c0fe2966517c2
  Stored in directory: /Users/paul/Library/Caches/pip/wheels/78/68/94/36d02be55927bbe4867f00adce8e6b1e3d79fa6b66cb508ca6
Successfully built flask-graphql graphql-server-core greenlet promise sqlalchemy
Installing collected packages: rx, promise, markupsafe, graphql-core, jinja2, itsdangerous, greenlet, graphql-relay, click, aniso8601, urllib3, sqlalchemy, singledispatch, idna, graphql-server-core, graphene, flask, chardet, certifi, requests, pyjwt, graphene-sqlalchemy, flask-graphql
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 2.0.1
    Uninstalling MarkupSafe-2.0.1:
      Successfully uninstalled MarkupSafe-2.0.1
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 3.0.1
    Uninstalling Jinja2-3.0.1:
      Successfully uninstalled Jinja2-3.0.1
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 2.0.1
    Uninstalling itsdangerous-2.0.1:
      Successfully uninstalled itsdangerous-2.0.1
  Attempting uninstall: click
    Found existing installation: click 8.0.1
    Uninstalling click-8.0.1:
      Successfully uninstalled click-8.0.1
  Attempting uninstall: flask
    Found existing installation: Flask 2.0.1
    Uninstalling Flask-2.0.1:
      Successfully uninstalled Flask-2.0.1
Successfully installed aniso8601-7.0.0 certifi-2020.12.5 chardet-4.0.0 click-8.0.0 flask-2.0.0 flask-graphql-2.0.1 graphene-2.1.8 graphene-sqlalchemy-2.3.0 graphql-core-2.3.2 graphql-relay-2.0.1 graphql-server-core-1.2.0 greenlet-1.1.0 idna-2.10 itsdangerous-2.0.0 jinja2-3.0.0 markupsafe-2.0.0 promise-2.3 pyjwt-2.1.0 requests-2.25.1 rx-1.6.1 singledispatch-3.6.1 sqlalchemy-1.4.15 urllib3-1.26.4
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.

% poetry run ./main.py           
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from gql_server.app import create_server
  File "/Users/paul/code/CSCI334Project/server/gql_server/app.py", line 3, in <module>
    from flask import Flask, request, safe_join, send_file
ModuleNotFoundError: No module named 'flask'
```

**Comment by cactuspoint** [comment]
```
% poetry run ./main.py   

  OSError

  [Errno 8] Exec format error: './main.py'

  at /opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:597 in _execvpe
       593│         argrest = (args,)
       594│         env = environ
       595│ 
       596│     if path.dirname(file):
    →  597│         exec_func(file, *argrest)
       598│         return
       599│     saved_exc = None
       600│     path_list = get_exec_path(env)
       601│     if name != 'nt':
```

**Comment by iommu** [comment]
Command is now 
```
poetry run python ./main.py
```

**Comment by cactuspoint** [comment]
Working server setup command:
```
% poetry run python ./main.py
 * Serving Flask app 'gql_server.app' (lazy loading)
 * Running on http://10.0.1.5:5000/ (Press CTRL+C to quit)
```

Resolved :)
